---
params:
  cohort_name: 'Cohort Name'
  author_name: 'Firstname LASTNAME'
  output_directory: './'
title: 'RHAPSODY WP3 Pre-Diabetes Analysis Check (Version 1.1.1)'
subtitle: '`r params$cohort_name`'
author: '`r params$author_name`'
date: '`r format(Sys.Date(), "%d %B %Y")`'
monofont: 'Source Code Pro'
monofontoptions: 'Scale=0.7'
output:
  pdf_document:
    toc: false
    fig_width: 9.45
    fig_height: 7.05
    number_sections: true
    df_print: kable
    latex_engine: pdflatex
---

```{r setup, include = FALSE}
working_directory <- params$output_directory

knitr::opts_chunk$set(
  cache = FALSE,
  echo = FALSE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  include = TRUE,
  tidy = FALSE,
  crop = TRUE,
  autodep = TRUE,
  fig.align = 'center',
  fig.pos = '!H',
  dpi = 120,
  size = 'small', 
  results = 'asis',
  dev = 'png',
  fig.path = paste0(tempdir(), '/')
)

library(parallel)
library(tidyverse)
library(scales)
library(gridExtra)
library(ggpubr)

options(stringsAsFactors = FALSE)
base_size <- 12
ggplot2::theme_set(ggplot2::theme_light(base_size = base_size))
```

```{r ggmanhattan}
# devtools::source_url('https://github.com/mcanouil/DEV/raw/master/R/ggmanhattan.R')
ggmanhattan <- function(data, x_chr, x_pos, y_pval, y_trans = TRUE, x_space = 5e7, ...) {
  require(tidyverse)
  require(scales)
  args_values <- list(...)
  all_args <- names(args_values)
  old_args <- intersect(
    all_args,
    c("chr", "position", "y", "sep", "ytrans")
  )
  setdiff(
    all_args, 
    c("data", "x_chr", "x_pos", "y_pval", "y_trans", "x_space", "chr", "position", "y", "sep", "ytrans")
  ) %>% 
    purrr::map(.x = ., .f = ~message(paste0("Argument '", .x, "' is deprecated!")))
  if (length(old_args)!=0) {
    for (iarg in old_args) {
      message(paste0(
        "Argument '", 
        iarg, 
        "' is deprecated, use '", 
        switch(
          EXPR = iarg,
          "chr" = {"x_chr"},
          "position" = {"x_pos"},
          "y" = {"y_pval"},
          "sep" = {"x_space"},
          "ytrans" = {"y_trans"}
        ), 
        "' instead!"
      ))
    }
    
    for (iexpr in intersect(old_args, c("chr", "position", "y", "sep", "ytrans"))) {
      switch(
        EXPR = iexpr,
        "chr" = {x_chr <- args_values[["chr"]]},
        "position" = {x_pos <- args_values[["position"]]},
        "y" = {y_pval <- args_values[["y"]]},
        "sep" = {x_space <- args_values[["sep"]]},
        "ytrans" = {y_trans <- args_values[["ytrans"]]}
      )
    }
  }
    
  pval_trans <- function() {
    neglog10_breaks <- function(n = 5) {
      function(x) {
        rng <- -log(range(x, na.rm = TRUE), base = 10)
        min <- 0
        max <- floor(rng[1])
        if (max == min) {
          return(10^-min)
        } else {
          by <- floor((max - min) / n) + 1
          return(10^-seq(min, max, by = by))
        }
      }
    }
    scales::trans_new(
      name = "pval",
      transform = function(x) {
        -log(x, 10)
      },
      inverse = function(x) {
        10^-x
      },
      breaks = neglog10_breaks(),
      domain = c(1e-300, 1),
      format = function(x) {
        parse(
          text = scales::scientific_format()(x) %>%
            gsub("1e+00", "1", ., fixed = TRUE) %>%
            gsub("e", " %*% 10^", .)
        )
      }
    )
  }

  data <- data %>% 
    dplyr::rename(
      x_chr = !!x_chr,
      x_pos = !!x_pos,
      y_pval = !!y_pval
    ) %>% 
    dplyr::mutate(
      x_chr = x_chr %>% 
        toupper() %>% 
        gsub("CHR", "", .) %>% 
        factor(., levels = c(seq(22), "X", "Y")),
      x_pos = as.integer(x_pos),
      y_pval = as.numeric(y_pval)
    ) %>% 
    dplyr::filter(!is.na(x_chr) & !is.na(x_pos)) %>% 
    dplyr::arrange(x_chr, x_pos) %>% 
    dplyr::group_by(x_chr) %>% 
    dplyr::mutate(x_pos = x_pos - min(x_pos) + 1) %>% 
    dplyr::ungroup()

  data <- dplyr::full_join(
    x = data,
    y = data %>% 
      dplyr::group_by(x_chr) %>% 
      dplyr::summarise(x_pos = max(x_pos)) %>% 
      dplyr::mutate(x_start = c(0, cumsum(x_pos[-length(x_pos)]+x_space))) %>% 
      dplyr::select(x_chr, x_start),
    by = "x_chr"
  ) %>% 
    dplyr::mutate(
      x_pos = x_pos + x_start
    )

  x_breaks <- data %>% 
    dplyr::group_by(x_chr) %>% 
    dplyr::summarise(x_med = min(x_pos)+diff(range(x_pos))/2) %>% 
    dplyr::select(x_chr, x_med)

  p <- ggplot2::ggplot(data = data, mapping = ggplot2::aes(x = x_pos, y = y_pval, colour = x_chr)) +
    ggplot2::geom_point(size = 1.5, shape = 21, na.rm = TRUE, show.legend = FALSE) +
    ggplot2::scale_colour_manual(
      values = rep(scales::viridis_pal(begin = 1/4, end = 3/4)(2), 12)
    ) +
    ggplot2::scale_x_continuous(
      breaks = x_breaks[["x_med"]],
      labels = x_breaks[["x_chr"]],
      limits = range(data[["x_pos"]]),
      expand = c(0.01, 0)
    ) +
    ggplot2::labs(y = y_pval, x = x_chr)
  if (y_trans) {
    p <- p +
      ggplot2::scale_y_continuous(trans = pval_trans(), limits = c(1, NA))
  }
  return(p)
}
```

```{r ggqqplot}
# devtools::source_url('https://github.com/mcanouil/DEV/raw/master/R/ggqqplot.R')
ggqqplot <- function (data, col_names = colnames(data), point_size = 1) {
  pval_trans <- function() {
    neglog10_breaks <- function(n = 5) {
      function(x) {
        # if (any(x==0)) {
        #   x[x==0]<- .Machine$double.xmin 
        #   message(paste("[pval_trans] Some values were equal to zero and have been change to:", .Machine$double.xmin))
        # }
        rng <- -log(range(x, na.rm = TRUE), base = 10)
        min <- 0 # ceiling(rng[2])
        max <- floor(rng[1])
        if (max == min) {
          return(10^-min)
        } else {
          by <- floor((max - min) / n) + 1
          return(10^-seq(min, max, by = by))
        }
      }
    }
    trans_new(
      name = "pval",
      transform = function(x) {
        -log(x, 10)
      },
      inverse = function(x) {
        10^-x
      },
      breaks = neglog10_breaks(),
      domain = c(1e-300, 1),
      format = function(x) {
        parse(
          text = scientific_format()(x) %>%
            gsub("1e+00", "1", ., fixed = TRUE) %>%
            gsub("e", " %*% 10^", .)
        )
      }
    )
  }
  
  if (is.null(ncol(data))) {
    data <- data.frame(X1 = data)
  }

  if (is.null(col_names)) {
    colnames(data) <- col_names
  }
  
  set_colour <- function() {
    ggplot2::theme_get()$plot.background$colour %>% 
      grDevices::col2rgb() %>% 
      range() %>% 
      sum() %>% 
      (function(.x){
        if ((.x* 100 * 0.5/255)>=50) {
          "black"
        } else {
          "white"
        }
      })()
  }
  
  data %>% 
    as.data.frame() %>% 
    tidyr::gather(key = "group", value = "obspval") %>% 
    group_by(group) %>% 
    arrange(obspval) %>% 
    mutate(
      exppval = (seq_len(n()) - 0.5)/length(seq_len(n())),
      gc = median(qnorm(obspval/2)^2, na.rm = TRUE)/qchisq(0.5, df = 1),
      logobspval = -log10(obspval),
      logexppval = -log10(exppval)
    ) %>% 
    ungroup() %>% 
    mutate(
      labels = paste0("lambda[", group, "]==", round(gc, digits = 3)),
      labels = factor(labels, levels = unique(labels))
    ) %>% 
    ggplot2::ggplot() +
      ggplot2::geom_abline(intercept = 0, slope = 1, colour = set_colour()) +
      ggplot2::geom_point(ggplot2::aes_string(x = "exppval", y = "obspval", colour = "labels", shape = "labels"), size = point_size) +
      ggplot2::scale_x_continuous(trans = pval_trans()) +
      ggplot2::scale_y_continuous(trans = pval_trans()) +
      ggplot2::scale_colour_manual(labels = parse_format(), values = scales::viridis_pal(begin = 0.5, end = 0.5)(1)) +
      ggplot2::scale_shape_discrete(solid = FALSE, labels = parse_format()) +
      ggplot2::labs(
        x = "Expected P-value", 
        y = "Observed P-value", 
        title = "Q-Q plot",
        colour = NULL,
        shape = NULL
      )
}
```


```{r check_figures}
logs <- list.files(path = working_directory, pattern = "*.log$", recursive = TRUE, full.names = TRUE) %>% 
  purrr::map_chr(.f = readLines) %>% 
  data.frame(snp = .) %>% 
  dplyr::filter(snp!="")

for (file in list.files(paste0(working_directory, '/results_to_send'), full.names = TRUE)) {
  cat("\n\n#", gsub(".*/[A-Za-z_]*_([0-9]+)_(.*).csv.gz", "Chromosome \\1 (\\2)", file), "\n")
  tmp <- readr::read_csv(file = file)
  p1 <- ggplot2::ggplot(data = tmp, mapping = ggplot2::aes(x = seq(length(position)), y = position)) +
    ggplot2::geom_point(colour = scales::viridis_pal(begin = 0.75, end = 0.75)(1)) +
    ggplot2::scale_y_continuous(labels = function(x) { 
      parse(
        text = scales::scientific_format()(x) %>% 
          gsub("0e+00", "0", ., fixed = TRUE) %>% 
          gsub("e", " %*% 10^", .)
      ) 
    }) +
    ggplot2::scale_x_continuous(labels = function(x) { 
      parse(
        text = scales::scientific_format()(x) %>% 
          gsub("0e+00", "0", ., fixed = TRUE) %>% 
          gsub("e", " %*% 10^", .)
      ) 
    }) +
    ggplot2::labs(x = "Sequential position", y = "Chromosome position") +
    ggplot2::theme(plot.margin = ggplot2::margin(t = base_size/2, r = base_size, b = base_size/2, l = base_size/2))
  p2 <- ggqqplot(data = tmp[, "pval", drop = FALSE]) +
    ggplot2::theme(legend.position = c(1, 0), legend.justification = c(1.05, -0.05)) +
    ggplot2::labs(title = NULL)
  p3 <- ggmanhattan(data = tmp, x_chr = "chr", x_pos = "position", y_pval = "pval") +
    ggplot2::labs(x = "Chromosome", y = "P-Value")
  
  ggpubr::ggarrange(
    ggpubr::ggarrange(
      p1, p2,
      ncol = 2,
      labels = c("A", "B")
    ),
    p3,
    nrow = 2,
    labels = c("", "C")
  ) %>%
    gridExtra::arrangeGrob(
      top = ggpubr::text_grob(
        label = gsub(".*/[A-Za-z_]*_([0-9]+)_(.*).csv.gz", "Chromosome \\1 (\\2)", file), 
        color = "black", 
        face = "bold", 
        size = 16
      ),
      left = "",
      right = "", 
      bottom = ""
    ) %>%
    ggpubr::as_ggplot() %>% 
    print()
  
  if (knitr:::is_latex_output()) {cat('\\clearpage')}
  cat("\n")
}
```

