FROM umr8199/rhapsody:latest

RUN cd /home/rhapsody \
  && rm -R /WP3/scripts \
  && git clone https://github.com/mcanouil/RHAPSODY.git /WP3/scripts

RUN git -C /home/rhapsody/WP3/scripts pull origin master \
  && chown -R rhapsody:rhapsody /home/rhapsody/ \
  && chown -R rhapsody:rhapsody /home/rhapsody/WP3/scripts/.git \
  && chmod -R 777 /home/rhapsody/WP3/scripts/.git

  
EXPOSE 8787


CMD ["/bin/sh", "/tmp/boot.sh"]
