FROM umr1283/rhapsody:latest

RUN rm -R /home/rhapsody/WP3 \
  && mkdir -p -m 777 /home/rhapsody/WP3 \
  && cd /home/rhapsody/WP3 \
  && git clone https://github.com/mcanouil/RHAPSODY.git scripts \
  && chown -R rhapsody:rhapsody /home/rhapsody/ \
  && chown -R rhapsody:rhapsody /home/rhapsody/WP3/scripts/.git \
  && chmod -R 777 /home/rhapsody/WP3/scripts/.git

  
EXPOSE 8787


CMD ["/bin/sh", "/tmp/boot.sh"]
