on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 0 01 */3 *'

name: pull-docker

jobs:
  pull-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker images
        run: |
          timeout 1s docker pull umr1283/rhapsody:latest || true
          timeout 1s docker pull umr1283/rhapsody:1.3.0 || true
          timeout 1s docker pull umr1283/rhapsody:1.2.24 || true
