on:
  workflow_dispatch:

name: archive-docker

jobs:
  pull-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker pull docker.io/umr1283/rhapsody:1.3.0
          docker tag docker.io/umr1283/rhapsody:1.3.0 ghcr.io/mcanouil/rhapsody:1.3.0
          docker push ghcr.io/mcanouil/rhapsody:1.3.0
          docker tag docker.io/umr1283/rhapsody:1.3.0 ghcr.io/mcanouil/rhapsody:latest
          docker push ghcr.io/mcanouil/rhapsody:latest
